name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 触发分支

permissions:
  contents: write # 必须赋予写权限以推送新分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies 🔧
        run: pnpm install

      - name: Build 🏗️
        run: pnpm build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # 打包产物目录
          branch: gh-pages # 产物存放的目标分支
